### PR TITLE
Fix unit test failures

### PR DESCRIPTION
**Pull request by SimonStJG**
Hello,

I was having a look at OrgProbe and I found some of the unit tests weren't passing, I've fixed them up a bit, hope this helps. 

I also found that probe.py was using a mix of tabs and spaces, since the majority of the lines were using tabs, I converted it all to tabs.  

Simon

### CODE REVIEW

**Comment by EvelynSubarrow** [comment]
Is there any particular reason for choosing tabs as opposed to spaces? The official style guide [does prefer spaces](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces).

**Comment by SimonStJG** [comment]
Yes you're right. I wanted to make the smallest change possible which would give consistency.

If the maintainer wants to just use spaces, I don't mind opening another pull request?

**Comment by graphiclunarkid** [comment]
Thanks very much for the contribution, @SimonStJG!

Can I suggest we separate these out into two separate pull requests: one to fix up the unit tests and a second to make the whitespace consistent? That way the diffs will show our future selves what we did to fix the unit tests without the details being masked by lots of unrelated line changes.

My opinion on whitespace is that since we're taking the time to improve things we should follow the official style guide, as @EvelynSubarrow suggested. That will let us use automatic linting tools with fewer difficulties in future too.

**Comment by dantheta** [comment]
Sorry - the inconsistent whitespace is my doing - several years ago I used to prefer tabs to spaces (against the style guide), because it was fewer bytes, and because it would allow the reader to set the indent level in their editor to their preference (2,3, 4 or 8 columns).  In the subsequent years, I switched to the PEP8 preferred setting, but never quite remembered this whenever I was editing old code.

**Comment by SimonStJG** [comment]
No worries, I'll separate this into two pull requests tonight.

**Comment by SimonStJG** [comment]
This pr is now just fixing the unit test failures.

**Pull request merged**
